### PR TITLE
Adapt to coq/coq#17585 (revised warning API)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ckeller** [comment]
Thanks @SkySkimmer , I am going to merge.
Just for my own CI: I do not know how to automatically create a docker image based on coq-master that contains the PR that requires the change. Any idea/example?

**Comment by SkySkimmer** [comment]
Do not merge now, this must wait for the upstream PR. When the upstream PR is merged someone will comment here asking to merge.

> Just for my own CI: I do not know how to automatically create a docker image based on coq-master that contains the PR that requires the change. Any idea/example?

I don't think anyone does that. We generally don't get errors as the upstream PR tests this code in its CI.

**Comment by ckeller** [comment]
> Do not merge now, this must wait for the upstream PR. When the upstream PR is merged someone will comment here asking to merge.

Ok, thanks. It somehow solves my problem.

> > Just for my own CI: I do not know how to automatically create a docker image based on coq-master that contains the PR that requires the change. Any idea/example?
> 
> I don't think anyone does that. We generally don't get errors as the upstream PR tests this code in its CI.

I do not only test compilation and installation, but also unit tests.

**Comment by proux01** [comment]
@ckeller upstream PR merged, this can now be merged

**Comment by proux01** [comment]
Thanks!

**Pull request merged**
